### ISSUE TITLE
About pre-training

### ISSUE THREAD

**Issue by Simon-Stma** [yihong-97/Source-free_IAPC#1]
I'm very interested in your work, and I would like to train on my own dataset. I noticed that you provided pre-trained weights for gta-cityscape in your work. Now, I want to use pre-trained weights with my own dataset. Could you provide the corresponding pre-training code?

**Comment by yihong-97** [comment]
please refer [url](https://github.com/LTTM/UDAclustering), We adopt the same [way ](https://github.com/LTTM/UDAclustering/tools/train_source.py)of source domain pre-training
