### ISSUE TITLE
For synthia-cityscapes part of the code

### ISSUE THREAD

**Issue by MysteriousT** [yihong-97/Source-free_IAPC#2]
Hello, author, I am very interested in the research in this field, and I also show my respect to you. gta5-cityscape and synthia cityscapes are mentioned in the paper, but the code given only includes the first part. Can we send out the code of synthia cityscapes? I'd like to know more about this area of work, thank you

**Comment by yihong-97** [comment]
Hi, thank you for your interest in our work. 
In fact, for the synthia-to-cityscapes scenario, the code has hardly changed; you just need to set the parameter NUM_CLASSES=16.

**Comment by yihong-97** [comment]
Hi, thank you for your interest in our work. In fact, for the synthia-to-cityscapes scenario, the code has hardly changed; you just need to set the parameters NUM_CLASSES=16 and NUM_STEPS_STOP=5000.
