### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by woldier** [yihong-97/Source-free_IAPC#5]
https://github.com/yihong-97/Source-free-IAPC/blob/e6be2a7e43766ac2b1d27f8eeb5f7984fdb4ee1c/GTA5/trainer.py#L239

`feat_i`  is an incorrect reference to a variable, the amount of change was not declared and therefore caused the error

**Comment by woldier** [comment]
https://github.com/yihong-97/Source-free-IAPC/blob/e6be2a7e43766ac2b1d27f8eeb5f7984fdb4ee1c/GTA5/trainer.py#L248-L249
this code has a reshape error. Because clu_probabilitys shpe is `[b,h*w,c]`,
 we cant use func `view` directly to make the shape change to `[b,c,h,w]`.

We first change the shape from `[b,h*w,c]` to `[b,h,w,c]` , and then we change the shape to `[b,c,h,w]`
We can actually do an experiment to verify it.
```python
... 
clu_probabilitys_copy = torch.stack(clu_probability_list, dim=0)
clu_probabilitys_copy = clu_probabilitys_copy.view(label_contrast.size(0),label_contrast.size(2),
                                                 label_contrast.size(3), self.num_classes).permute(0, 3, 1, 2).contiguous()

torch.allclose(clu_probabilitys_copy, clu_probabilitys)
```
We're gonna get:
```shell
False
```

**Comment by yihong-97** [comment]
Thanks for pointing out. Indeed, there was a bug in our code, which was caused by two mistakenly-enabled error comments. We have already updated the code and it is available at https://github.com/yihong-97/Source-free-IAPC/blob/576a15a7847c83af727f6067aab99e6769b8d928/GTA5/trainer.py#L201-202

**Comment by woldier** [comment]
Thanks! @yihong-97 
By the way, https://github.com/yihong-97/Source-free-IAPC/issues/5#issuecomment-2514322260
https://github.com/yihong-97/Source-free-IAPC/blob/576a15a7847c83af727f6067aab99e6769b8d928/GTA5/trainer.py#L250-L251
directly use `view` function to reshape `bx(h*w)xc` to `bxcxhxw` is a wrong operation.

**Comment by yihong-97** [comment]
Thanks. We have already made the correction.
